version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build

    steps:
      - checkout
      - run:
          name:    Setup
          command: stack setup
      - run:
          name:    Install
          command: stack install
      - run:
          name:    Test
          command: stack test
      - run:
          name:    Create artifacts directory
          command: |
            mkdir -p /tmp/artifacts;
            cp .stack-work/logs/json-autotype-1.1.*.log          /tmp/artifacts/json-autotype.log;
            cp .stack-work/dist/*/Cabal-*/json-autotype-*.tar.gz /tmp/artifacts/json-autotype.tar.gz
      - store_artifacts:
          path:        /tmp/artifacts/json-autotype.log
      - store_artifacts:
          path:        /tmp/artifacts/json-autotype.tar.gz
