version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build

    steps:
      - checkout
      - run:
          name:    Setup
          command: stack setup
      - run:
          name:    Install
          command: stack install
      - run:
          name:    Test
          command: stack test
      - store_artifacts:
          path:        .stack-work/logs/json-autotype-1.1.*.log
          destination: json-autotype.log
      - store_artifacts:
          path:        .stack-work/dist/*/Cabal-*/json-autotype-*.tar.gz
          destination: json-autotype.tar.gz
